version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    container
    links:
      - mongo:app_db
  mongo:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
    hostname:
      - mongo